services:
  SKYKOI-gateway:
    image: ${SKYKOI_IMAGE:-SKYKOI:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      SKYKOI_GATEWAY_TOKEN: ${SKYKOI_GATEWAY_TOKEN}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${SKYKOI_CONFIG_DIR}:/home/node/.SKYKOI
      - ${SKYKOI_WORKSPACE_DIR}:/home/node/.SKYKOI/workspace
    ports:
      - "${SKYKOI_GATEWAY_PORT:-18789}:18789"
      - "${SKYKOI_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${SKYKOI_GATEWAY_BIND:-lan}",
        "--port",
        "18789",
      ]

  SKYKOI-cli:
    image: ${SKYKOI_IMAGE:-SKYKOI:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      SKYKOI_GATEWAY_TOKEN: ${SKYKOI_GATEWAY_TOKEN}
      BROWSER: echo
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${SKYKOI_CONFIG_DIR}:/home/node/.SKYKOI
      - ${SKYKOI_WORKSPACE_DIR}:/home/node/.SKYKOI/workspace
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]
