export const browserCoreExamples = [
  "SKYKOI browser status",
  "SKYKOI browser start",
  "SKYKOI browser stop",
  "SKYKOI browser tabs",
  "SKYKOI browser open https://example.com",
  "SKYKOI browser focus abcd1234",
  "SKYKOI browser close abcd1234",
  "SKYKOI browser screenshot",
  "SKYKOI browser screenshot --full-page",
  "SKYKOI browser screenshot --ref 12",
  "SKYKOI browser snapshot",
  "SKYKOI browser snapshot --format aria --limit 200",
  "SKYKOI browser snapshot --efficient",
  "SKYKOI browser snapshot --labels",
];

export const browserActionExamples = [
  "SKYKOI browser navigate https://example.com",
  "SKYKOI browser resize 1280 720",
  "SKYKOI browser click 12 --double",
  'SKYKOI browser type 23 "hello" --submit',
  "SKYKOI browser press Enter",
  "SKYKOI browser hover 44",
  "SKYKOI browser drag 10 11",
  "SKYKOI browser select 9 OptionA OptionB",
  "SKYKOI browser upload /tmp/file.pdf",
  'SKYKOI browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "SKYKOI browser dialog --accept",
  'SKYKOI browser wait --text "Done"',
  "SKYKOI browser evaluate --fn '(el) => el.textContent' --ref 7",
  "SKYKOI browser console --level error",
  "SKYKOI browser pdf",
];
