export const browserCoreExamples = [
  "skykoi browser status",
  "skykoi browser start",
  "skykoi browser stop",
  "skykoi browser tabs",
  "skykoi browser open https://example.com",
  "skykoi browser focus abcd1234",
  "skykoi browser close abcd1234",
  "skykoi browser screenshot",
  "skykoi browser screenshot --full-page",
  "skykoi browser screenshot --ref 12",
  "skykoi browser snapshot",
  "skykoi browser snapshot --format aria --limit 200",
  "skykoi browser snapshot --efficient",
  "skykoi browser snapshot --labels",
];

export const browserActionExamples = [
  "skykoi browser navigate https://example.com",
  "skykoi browser resize 1280 720",
  "skykoi browser click 12 --double",
  'SkyKoi browser type 23 "hello" --submit',
  "skykoi browser press Enter",
  "skykoi browser hover 44",
  "skykoi browser drag 10 11",
  "skykoi browser select 9 OptionA OptionB",
  "skykoi browser upload /tmp/file.pdf",
  'SkyKoi browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "skykoi browser dialog --accept",
  'SkyKoi browser wait --text "Done"',
  "skykoi browser evaluate --fn '(el) => el.textContent' --ref 7",
  "skykoi browser console --level error",
  "skykoi browser pdf",
];
