#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${SKYKOI_INSTALL_E2E_IMAGE:-${SKYKOI_INSTALL_E2E_IMAGE:-SKYKOI-install-e2e:local}}"
INSTALL_URL="${SKYKOI_INSTALL_URL:-${SKYKOI_INSTALL_URL:-https://SKYKOI.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
SKYKOI_E2E_MODELS="${SKYKOI_E2E_MODELS:-${SKYKOI_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e SKYKOI_INSTALL_URL="$INSTALL_URL" \
  -e SKYKOI_INSTALL_TAG="${SKYKOI_INSTALL_TAG:-${SKYKOI_INSTALL_TAG:-latest}}" \
  -e SKYKOI_E2E_MODELS="$SKYKOI_E2E_MODELS" \
  -e SKYKOI_INSTALL_E2E_PREVIOUS="${SKYKOI_INSTALL_E2E_PREVIOUS:-${SKYKOI_INSTALL_E2E_PREVIOUS:-}}" \
  -e SKYKOI_INSTALL_E2E_SKIP_PREVIOUS="${SKYKOI_INSTALL_E2E_SKIP_PREVIOUS:-${SKYKOI_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
